// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PlaylistRecommenderAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250311190945_AddSearchHistoryTable")]
    partial class AddSearchHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("RecommendedPlaylist")
                        .HasColumnType("longtext")
                        .HasColumnName("recommended_playlist");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("search_date");

                    b.Property<string>("SearchedSongs")
                        .HasColumnType("longtext")
                        .HasColumnName("searched_songs");

                    b.HasKey("Id");

                    b.ToTable("SearchHistory");
                });

            modelBuilder.Entity("UserSearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecommendedPlaylist")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SearchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SearchedSongs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserSearches");
                });
#pragma warning restore 612, 618
        }
    }
}
